### ISSUE TITLE
A question about login

### ISSUE THREAD

**Issue by VolcanoWCAN** [kehm/ehrblockchainapplication#1]
Hi, author:
**Here, I have another question about this project. And it's about the java application side:**
When the program is running, we need to log in. In this case, I enter "admin" in the login window, and it will prompt the login failure. Then I used "admin" again, I found that it can log in successfully. I found that no password was used during this process. And a folder called "user " occurs. There are some information in this folder. I want to know how this is done for user authentication?  What is the reason for this?
Thank you very much!

**Comment by kehm** [comment]
As far as I remember: 
If the application cannot find a matching identity in the "user" folder, it will try to register the new identity with the Fabric CA and subsequently enroll the identity (as a convenience during testing, so that you don't have to register every user with the CA beforehand).
Depending on how the CA is configured, the CA will either approve or reject the registration and return a certificate/key for the identity, which is then stored in the "user" folder for future use.

However, I suggest you look into the new Fabric Gateway project (https://github.com/hyperledger/fabric-gateway-java), which is a new abstraction layer on top of the Fabric Java SDK. This is the new way to create Java applications for Fabric networks and is a lot easier to use than the full SDK I used in this project. 
You can find an example using the Fabric Gateway in this repo: https://github.com/hyperledger/fabric-samples/tree/master/fabcar/java/src/main/java/org/example. 
The wallet introduced in Fabric Gateway is essentially the same as the "user" folder that is created by this application.

I might do an update of this project some time later this year, using Gateway instead of the SDK.
